### ISSUE TITLE
got npm error

### ISSUE THREAD

**Issue by stayliv3** [GM-Alex/docker-phpapp#1]
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.37","npm":"1.4.28"})
npm ERR! Error: shasum check failed for /tmp/npm-5-1MpsllrF/registry.npmjs.org/rx/-/rx-2.5.3.tgz
npm ERR! Expected: 21adc7d80f02002af50dae97fd9dbf248755f566
npm ERR! Actual:   238c5c81d133fbeaee6d17ce297fc7b94c97ba8f
npm ERR! From:     https://registry.npmjs.org/rx/-/rx-2.5.3.tgz
npm ERR!     at /usr/lib/node_modules/npm/node_modules/sha/index.js:38:8
npm ERR!     at ReadStream.<anonymous> (/usr/lib/node_modules/npm/node_modules/sha/index.js:85:7)
npm ERR!     at ReadStream.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:944:16
npm ERR!     at process._tickCallback (node.js:448:13)
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Linux 4.1.10-boot2docker
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "bower"
npm ERR! cwd /
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! not ok code 0

**Comment by stayliv3** [comment]
don't konw how to upgrade...

**Comment by GM-Alex** [comment]
You have to build the docker container by your own.

**Comment by stayliv3** [comment]
it seems my network problem.thanks for your help.
